/run/numberOfThreads 1
/run/initialize
/vis/open OGL
/vis/viewer/set/viewpointVector 1 1 1
/vis/drawVolume
/vis/viewer/set/autoRefresh true
#/vis/scene/add/axes 0 0 0 10 cm
/vis/scene/add/trajectories smooth
/vis/scene/add/eventID
/vis/scene/endOfEventAction accumulate -1
/vis/ogl/set/displayListLimit 5000000
/vis/modeling/trajectories/create/drawByParticleID
/gun/particle mu-
/gun/energy 10 MeV
/vis/modeling/trajectories/drawByParticleID-0/set gamma blue
/vis/modeling/trajectories/drawByParticleID-0/set opticalphoton green
/vis/modeling/trajectories/drawByParticleID-0/set mu- yellow
/vis/modeling/trajectories/drawByParticleID-0/set e- orange
/vis/modeling/trajectories/drawByParticleID-0/set nu_mu magenta
/vis/modeling/trajectories/drawByParticleID-0/set anti_nu_e red
